mcp:
  client:
    stdio:
      #          servers-configuration: classpath:./mcp-servers-config.json
      connections:
        spring-ai-playwright:
          command: java
          args: -jar,C:\\Users\\13716\\AI-coder\\playwright\\target\\playwright-0.0.1-SNAPSHOT.jar